version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: diaries-postgres
    environment:
      POSTGRES_DB: diaries_db
      POSTGRES_USER: diaries_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diaries_user -d diaries_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diaries-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/diaries_db
      SPRING_DATASOURCE_USERNAME: diaries_user
      SPRING_DATASOURCE_PASSWORD: changeme
      JWT_SECRET: your-secret-key-change-this-in-production-minimum-256-bits
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - full-stack

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diaries-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    profiles:
      - full-stack

volumes:
  postgres_data:
